excluded:
  - Carthage
  - Pods

disabled_rules:
  - line_length
  - trailing_whitespace
  - function_parameter_count
  - identifier_name

custom_rules:
  private_outlets:
    included: ".*\\.swift"
    name: "Outlets should be private"
    regex: "IBOutlet[[:space:]]*weak[[:space:]]*var"
    severity: warning

  private_actions:
    included: ".*\\.swift"
    name: "Actions should be private"
    regex: "IBAction[[:space:]]*func"
    severity: warning
