# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    version = get_version_number(xcodeproj: "ShoppingManiac.xcodeproj", target: "ShoppingManiac")
    buildNumber = latest_testflight_build_number(version: version) + 1
    set_info_plist_value(path: "./ShoppingManiac/Resources/Info.plist", key: "CFBundleVersion", value: buildNumber.to_s)
    build_app(workspace: "ShoppingManiac.xcworkspace", scheme: "ShoppingManiac", clean: true, output_directory: "/tmp/fastlane", silent: true, suppress_xcode_output: true)
    upload_to_testflight
  end
end
